import matplotlib.pyplot as plt

def plotting(original_image, noisy_image, box_blur_recovered_image, weiner_recovered_image, gaussian_filtered_recovered_image,median_filtered_recovered_image):
    plt.figure(figsize=(16, 8))

    plt.subplot(2,3, 1)
    plt.imshow(original_image, cmap="gray")
    plt.title('Original Image')
    plt.axis('off')
    plt.subplot(2,3, 2)
    plt.imshow(noisy_image, cmap="gray")
    plt.title('Noisy Image' )
    plt.axis('off')
    plt.subplot(2,3, 3)
    plt.imshow(box_blur_recovered_image, cmap="gray")
    plt.title('Box blur recovered Image' )
    plt.axis('off')
    plt.subplot(2,3, 4)
    plt.imshow(weiner_recovered_image, cmap="gray")
    plt.title('Weiner recovered Image' )
    plt.axis('off')
    plt.subplot(2,3, 5)
    plt.imshow(gaussian_filtered_recovered_image, cmap="gray")
    plt.title('Gaussian filterred recovered Image' )
    plt.axis('off')
    plt.subplot(2,3, 6)
    plt.imshow(median_filtered_recovered_image, cmap="gray")
    plt.title('Median filterred recovered Image' )
    plt.axis('off')
    plt.show()